name: anaconda-publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/shimwell/miniconda

    steps:
      - uses: actions/checkout@v2

      - name: Install CQ dependencies
        run: |
            apt install -y libgl1-mesa-glx
      - name: Set up conda
        run: |
            conda config --set anaconda_upload no
      - name: Build and publish to conda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
            conda build conda -c cadquery -c conda-forge --config-file conda/conda_build_config.yaml
            conda convert /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --platform osx-64
            conda convert /usr/share/miniconda/conda-bld/linux-64/*.tar.bz2 --platform win-64
            anaconda upload -f /usr/share/miniconda/conda-bld/*/*.tar.bz2
